/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Apr 15 13:47:10 2020. */

#include "amount.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t waves_Amount_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, waves_Amount, asset_id, asset_id, 0),
    PB_FIELD(  2, INT64   , SINGULAR, STATIC  , OTHER, waves_Amount, amount, asset_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
