/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Apr 15 13:47:10 2020. */

#include "order.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t waves_AssetPair_fields[3] = {
    PB_FIELD(  1, BYTES   , SINGULAR, CALLBACK, FIRST, waves_AssetPair, amount_asset_id, amount_asset_id, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, waves_AssetPair, price_asset_id, amount_asset_id, 0),
    PB_LAST_FIELD
};

const pb_field_t waves_Order_fields[13] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, waves_Order, chain_id, chain_id, 0),
    PB_FIELD(  2, BYTES   , SINGULAR, CALLBACK, OTHER, waves_Order, sender_public_key, chain_id, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, CALLBACK, OTHER, waves_Order, matcher_public_key, sender_public_key, 0),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, waves_Order, asset_pair, matcher_public_key, &waves_AssetPair_fields),
    PB_FIELD(  5, UENUM   , SINGULAR, STATIC  , OTHER, waves_Order, order_side, asset_pair, 0),
    PB_FIELD(  6, INT64   , SINGULAR, STATIC  , OTHER, waves_Order, amount, order_side, 0),
    PB_FIELD(  7, INT64   , SINGULAR, STATIC  , OTHER, waves_Order, price, amount, 0),
    PB_FIELD(  8, INT64   , SINGULAR, STATIC  , OTHER, waves_Order, timestamp, price, 0),
    PB_FIELD(  9, INT64   , SINGULAR, STATIC  , OTHER, waves_Order, expiration, timestamp, 0),
    PB_FIELD( 10, MESSAGE , SINGULAR, STATIC  , OTHER, waves_Order, matcher_fee, expiration, &waves_Amount_fields),
    PB_FIELD( 11, INT32   , SINGULAR, STATIC  , OTHER, waves_Order, version, matcher_fee, 0),
    PB_FIELD( 12, BYTES   , REPEATED, CALLBACK, OTHER, waves_Order, proofs, version, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(waves_Order, asset_pair) < 65536 && pb_membersize(waves_Order, matcher_fee) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_waves_AssetPair_waves_Order)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(waves_Order, asset_pair) < 256 && pb_membersize(waves_Order, matcher_fee) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_waves_AssetPair_waves_Order)
#endif


/* @@protoc_insertion_point(eof) */
