/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Apr 15 13:47:10 2020. */

#include "recipient.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t waves_Recipient_fields[3] = {
    PB_ONEOF_FIELD(recipient,   1, BYTES   , ONEOF, STATIC  , FIRST, waves_Recipient, public_key_hash, public_key_hash, 0),
    PB_ONEOF_FIELD(recipient,   2, STRING  , ONEOF, STATIC  , UNION, waves_Recipient, alias, alias, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
