/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_WAVES_RECIPIENT_PB_H_INCLUDED
#define PB_WAVES_RECIPIENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _waves_Recipient {
  pb_size_t which_recipient;
  union {
    const char *public_key_hash;
    const char *alias;
  } recipient;
} waves_Recipient;

/* Initializer values for message structs */
#define waves_Recipient_init_default                                           \
  {                                                                            \
    0, {                                                                       \
      { {NULL}, NULL }                                                         \
    }                                                                          \
  }
#define waves_Recipient_init_zero                                              \
  {                                                                            \
    0, {                                                                       \
      { {NULL}, NULL }                                                         \
    }                                                                          \
  }

/* Field tags (for use in manual encoding/decoding) */
#define waves_Recipient_public_key_hash_tag 1
#define waves_Recipient_alias_tag 2

/* Struct field encoding specification for nanopb */
#define waves_Recipient_FIELDLIST(X, a)                                        \
  X(a, CALLBACK, ONEOF, BYTES,                                                 \
    (recipient, public_key_hash, recipient.public_key_hash), 1)                \
  X(a, CALLBACK, ONEOF, STRING, (recipient, alias, recipient.alias), 2)
extern bool waves_Recipient_callback(pb_istream_t *istream,
                                     pb_ostream_t *ostream,
                                     const pb_field_t *field);
#define waves_Recipient_CALLBACK waves_Recipient_callback
#define waves_Recipient_DEFAULT NULL

extern const pb_msgdesc_t waves_Recipient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define waves_Recipient_fields &waves_Recipient_msg

/* Maximum encoded size of messages (where known) */
/* waves_Recipient_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
