/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_WAVES_RECIPIENT_PB_H_INCLUDED
#define PB_WAVES_RECIPIENT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _waves_Recipient {
    pb_size_t which_recipient;
    union {
        pb_byte_t public_key_hash[20];
        char alias[30];
    } recipient;
} waves_Recipient;


/* Initializer values for message structs */
#define waves_Recipient_init_default             {0, {{0}}}
#define waves_Recipient_init_zero                {0, {{0}}}

/* Field tags (for use in manual encoding/decoding) */
#define waves_Recipient_public_key_hash_tag      1
#define waves_Recipient_alias_tag                2

/* Struct field encoding specification for nanopb */
#define waves_Recipient_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    FIXED_LENGTH_BYTES, (recipient,public_key_hash,recipient.public_key_hash),   1) \
X(a, STATIC,   ONEOF,    STRING,   (recipient,alias,recipient.alias),   2)
#define waves_Recipient_CALLBACK NULL
#define waves_Recipient_DEFAULT NULL

extern const pb_msgdesc_t waves_Recipient_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define waves_Recipient_fields &waves_Recipient_msg

/* Maximum encoded size of messages (where known) */
#define waves_Recipient_size                     31

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
