/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Wed Apr 15 13:47:10 2020. */

#ifndef PB_WAVES_TRANSACTION_PB_H_INCLUDED
#define PB_WAVES_TRANSACTION_PB_H_INCLUDED
#include <pb.h>

#include "amount.pb.h"

#include "recipient.pb.h"

#include "order.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _waves_CreateAliasTransactionData {
    pb_callback_t alias;
/* @@protoc_insertion_point(struct:waves_CreateAliasTransactionData) */
} waves_CreateAliasTransactionData;

typedef struct _waves_DataTransactionData {
    pb_callback_t data;
/* @@protoc_insertion_point(struct:waves_DataTransactionData) */
} waves_DataTransactionData;

typedef struct _waves_LeaseCancelTransactionData {
    pb_callback_t lease_id;
/* @@protoc_insertion_point(struct:waves_LeaseCancelTransactionData) */
} waves_LeaseCancelTransactionData;

typedef struct _waves_SetAssetScriptTransactionData {
    pb_callback_t asset_id;
    pb_callback_t script;
/* @@protoc_insertion_point(struct:waves_SetAssetScriptTransactionData) */
} waves_SetAssetScriptTransactionData;

typedef struct _waves_SetScriptTransactionData {
    pb_callback_t script;
/* @@protoc_insertion_point(struct:waves_SetScriptTransactionData) */
} waves_SetScriptTransactionData;

typedef struct _waves_UpdateAssetInfoTransactionData {
    pb_callback_t asset_id;
    pb_callback_t name;
    pb_callback_t description;
/* @@protoc_insertion_point(struct:waves_UpdateAssetInfoTransactionData) */
} waves_UpdateAssetInfoTransactionData;

typedef PB_BYTES_ARRAY_T(140) waves_Attachment_binary_value_t;
typedef struct _waves_Attachment {
    pb_size_t which_attachment;
    union {
        int64_t int_value;
        bool bool_value;
        waves_Attachment_binary_value_t binary_value;
        char string_value[140];
    } attachment;
/* @@protoc_insertion_point(struct:waves_Attachment) */
} waves_Attachment;

typedef struct _waves_BurnTransactionData {
    waves_Amount asset_amount;
/* @@protoc_insertion_point(struct:waves_BurnTransactionData) */
} waves_BurnTransactionData;

typedef PB_BYTES_ARRAY_T(32767) waves_DataTransactionData_DataEntry_binary_value_t;
typedef struct _waves_DataTransactionData_DataEntry {
    pb_callback_t key;
    pb_size_t which_value;
    union {
        int64_t int_value;
        bool bool_value;
        waves_DataTransactionData_DataEntry_binary_value_t binary_value;
        char string_value[32767];
    } value;
/* @@protoc_insertion_point(struct:waves_DataTransactionData_DataEntry) */
} waves_DataTransactionData_DataEntry;

typedef struct _waves_ExchangeTransactionData {
    int64_t amount;
    int64_t price;
    int64_t buy_matcher_fee;
    int64_t sell_matcher_fee;
    pb_callback_t orders;
/* @@protoc_insertion_point(struct:waves_ExchangeTransactionData) */
} waves_ExchangeTransactionData;

typedef struct _waves_GenesisTransactionData {
    pb_callback_t recipient_address;
    int64_t amount;
/* @@protoc_insertion_point(struct:waves_GenesisTransactionData) */
} waves_GenesisTransactionData;

typedef struct _waves_InvokeScriptTransactionData {
    waves_Recipient d_app;
    pb_callback_t function_call;
    pb_callback_t payments;
/* @@protoc_insertion_point(struct:waves_InvokeScriptTransactionData) */
} waves_InvokeScriptTransactionData;

typedef struct _waves_IssueTransactionData {
    pb_callback_t name;
    pb_callback_t description;
    int64_t amount;
    int32_t decimals;
    bool reissuable;
    pb_callback_t script;
/* @@protoc_insertion_point(struct:waves_IssueTransactionData) */
} waves_IssueTransactionData;

typedef struct _waves_LeaseTransactionData {
    waves_Recipient recipient;
    int64_t amount;
/* @@protoc_insertion_point(struct:waves_LeaseTransactionData) */
} waves_LeaseTransactionData;

typedef struct _waves_MassTransferTransactionData_Transfer {
    waves_Recipient address;
    int64_t amount;
/* @@protoc_insertion_point(struct:waves_MassTransferTransactionData_Transfer) */
} waves_MassTransferTransactionData_Transfer;

typedef struct _waves_PaymentTransactionData {
    pb_callback_t recipient_address;
    int64_t amount;
/* @@protoc_insertion_point(struct:waves_PaymentTransactionData) */
} waves_PaymentTransactionData;

typedef struct _waves_ReissueTransactionData {
    waves_Amount asset_amount;
    bool reissuable;
/* @@protoc_insertion_point(struct:waves_ReissueTransactionData) */
} waves_ReissueTransactionData;

typedef struct _waves_SponsorFeeTransactionData {
    waves_Amount min_fee;
/* @@protoc_insertion_point(struct:waves_SponsorFeeTransactionData) */
} waves_SponsorFeeTransactionData;

typedef struct _waves_MassTransferTransactionData {
    pb_callback_t asset_id;
    pb_callback_t transfers;
    waves_Attachment attachment;
/* @@protoc_insertion_point(struct:waves_MassTransferTransactionData) */
} waves_MassTransferTransactionData;

typedef struct _waves_TransferTransactionData {
    waves_Recipient recipient;
    waves_Amount amount;
    waves_Attachment attachment;
/* @@protoc_insertion_point(struct:waves_TransferTransactionData) */
} waves_TransferTransactionData;

typedef struct _waves_Transaction {
    int32_t chain_id;
    pb_callback_t sender_public_key;
    waves_Amount fee;
    int64_t timestamp;
    int32_t version;
    pb_size_t which_data;
    union {
        waves_GenesisTransactionData genesis;
        waves_PaymentTransactionData payment;
        waves_IssueTransactionData issue;
        waves_TransferTransactionData transfer;
        waves_ReissueTransactionData reissue;
        waves_BurnTransactionData burn;
        waves_ExchangeTransactionData exchange;
        waves_LeaseTransactionData lease;
        waves_LeaseCancelTransactionData lease_cancel;
        waves_CreateAliasTransactionData create_alias;
        waves_MassTransferTransactionData mass_transfer;
        waves_DataTransactionData data_transaction;
        waves_SetScriptTransactionData set_script;
        waves_SponsorFeeTransactionData sponsor_fee;
        waves_SetAssetScriptTransactionData set_asset_script;
        waves_InvokeScriptTransactionData invoke_script;
        waves_UpdateAssetInfoTransactionData update_asset_info;
    } data;
/* @@protoc_insertion_point(struct:waves_Transaction) */
} waves_Transaction;

typedef struct _waves_SignedTransaction {
    waves_Transaction transaction;
    pb_callback_t proofs;
/* @@protoc_insertion_point(struct:waves_SignedTransaction) */
} waves_SignedTransaction;

/* Default values for struct fields */

/* Initializer values for message structs */
#define waves_SignedTransaction_init_default     {waves_Transaction_init_default, {{NULL}, NULL}}
#define waves_Transaction_init_default           {0, {{NULL}, NULL}, waves_Amount_init_default, 0, 0, 0, {waves_GenesisTransactionData_init_default}}
#define waves_GenesisTransactionData_init_default {{{NULL}, NULL}, 0}
#define waves_PaymentTransactionData_init_default {{{NULL}, NULL}, 0}
#define waves_Attachment_init_default            {0, {0}}
#define waves_TransferTransactionData_init_default {waves_Recipient_init_default, waves_Amount_init_default, waves_Attachment_init_default}
#define waves_CreateAliasTransactionData_init_default {{{NULL}, NULL}}
#define waves_DataTransactionData_init_default   {{{NULL}, NULL}}
#define waves_DataTransactionData_DataEntry_init_default {{{NULL}, NULL}, 0, {0}}
#define waves_MassTransferTransactionData_init_default {{{NULL}, NULL}, {{NULL}, NULL}, waves_Attachment_init_default}
#define waves_MassTransferTransactionData_Transfer_init_default {waves_Recipient_init_default, 0}
#define waves_LeaseTransactionData_init_default  {waves_Recipient_init_default, 0}
#define waves_LeaseCancelTransactionData_init_default {{{NULL}, NULL}}
#define waves_BurnTransactionData_init_default   {waves_Amount_init_default}
#define waves_IssueTransactionData_init_default  {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define waves_ReissueTransactionData_init_default {waves_Amount_init_default, 0}
#define waves_SetAssetScriptTransactionData_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define waves_SetScriptTransactionData_init_default {{{NULL}, NULL}}
#define waves_ExchangeTransactionData_init_default {0, 0, 0, 0, {{NULL}, NULL}}
#define waves_SponsorFeeTransactionData_init_default {waves_Amount_init_default}
#define waves_InvokeScriptTransactionData_init_default {waves_Recipient_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define waves_UpdateAssetInfoTransactionData_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define waves_SignedTransaction_init_zero        {waves_Transaction_init_zero, {{NULL}, NULL}}
#define waves_Transaction_init_zero              {0, {{NULL}, NULL}, waves_Amount_init_zero, 0, 0, 0, {waves_GenesisTransactionData_init_zero}}
#define waves_GenesisTransactionData_init_zero   {{{NULL}, NULL}, 0}
#define waves_PaymentTransactionData_init_zero   {{{NULL}, NULL}, 0}
#define waves_Attachment_init_zero               {0, {0}}
#define waves_TransferTransactionData_init_zero  {waves_Recipient_init_zero, waves_Amount_init_zero, waves_Attachment_init_zero}
#define waves_CreateAliasTransactionData_init_zero {{{NULL}, NULL}}
#define waves_DataTransactionData_init_zero      {{{NULL}, NULL}}
#define waves_DataTransactionData_DataEntry_init_zero {{{NULL}, NULL}, 0, {0}}
#define waves_MassTransferTransactionData_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, waves_Attachment_init_zero}
#define waves_MassTransferTransactionData_Transfer_init_zero {waves_Recipient_init_zero, 0}
#define waves_LeaseTransactionData_init_zero     {waves_Recipient_init_zero, 0}
#define waves_LeaseCancelTransactionData_init_zero {{{NULL}, NULL}}
#define waves_BurnTransactionData_init_zero      {waves_Amount_init_zero}
#define waves_IssueTransactionData_init_zero     {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}}
#define waves_ReissueTransactionData_init_zero   {waves_Amount_init_zero, 0}
#define waves_SetAssetScriptTransactionData_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define waves_SetScriptTransactionData_init_zero {{{NULL}, NULL}}
#define waves_ExchangeTransactionData_init_zero  {0, 0, 0, 0, {{NULL}, NULL}}
#define waves_SponsorFeeTransactionData_init_zero {waves_Amount_init_zero}
#define waves_InvokeScriptTransactionData_init_zero {waves_Recipient_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define waves_UpdateAssetInfoTransactionData_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define waves_CreateAliasTransactionData_alias_tag 1
#define waves_DataTransactionData_data_tag       1
#define waves_LeaseCancelTransactionData_lease_id_tag 1
#define waves_SetAssetScriptTransactionData_asset_id_tag 1
#define waves_SetAssetScriptTransactionData_script_tag 2
#define waves_SetScriptTransactionData_script_tag 1
#define waves_UpdateAssetInfoTransactionData_asset_id_tag 1
#define waves_UpdateAssetInfoTransactionData_name_tag 2
#define waves_UpdateAssetInfoTransactionData_description_tag 3
#define waves_Attachment_int_value_tag           1
#define waves_Attachment_bool_value_tag          2
#define waves_Attachment_binary_value_tag        3
#define waves_Attachment_string_value_tag        4
#define waves_BurnTransactionData_asset_amount_tag 1
#define waves_DataTransactionData_DataEntry_int_value_tag 10
#define waves_DataTransactionData_DataEntry_bool_value_tag 11
#define waves_DataTransactionData_DataEntry_binary_value_tag 12
#define waves_DataTransactionData_DataEntry_string_value_tag 13
#define waves_DataTransactionData_DataEntry_key_tag 1
#define waves_ExchangeTransactionData_amount_tag 1
#define waves_ExchangeTransactionData_price_tag  2
#define waves_ExchangeTransactionData_buy_matcher_fee_tag 3
#define waves_ExchangeTransactionData_sell_matcher_fee_tag 4
#define waves_ExchangeTransactionData_orders_tag 5
#define waves_GenesisTransactionData_recipient_address_tag 1
#define waves_GenesisTransactionData_amount_tag  2
#define waves_InvokeScriptTransactionData_d_app_tag 1
#define waves_InvokeScriptTransactionData_function_call_tag 2
#define waves_InvokeScriptTransactionData_payments_tag 3
#define waves_IssueTransactionData_name_tag      1
#define waves_IssueTransactionData_description_tag 2
#define waves_IssueTransactionData_amount_tag    3
#define waves_IssueTransactionData_decimals_tag  4
#define waves_IssueTransactionData_reissuable_tag 5
#define waves_IssueTransactionData_script_tag    6
#define waves_LeaseTransactionData_recipient_tag 1
#define waves_LeaseTransactionData_amount_tag    2
#define waves_MassTransferTransactionData_Transfer_address_tag 1
#define waves_MassTransferTransactionData_Transfer_amount_tag 2
#define waves_PaymentTransactionData_recipient_address_tag 1
#define waves_PaymentTransactionData_amount_tag  2
#define waves_ReissueTransactionData_asset_amount_tag 1
#define waves_ReissueTransactionData_reissuable_tag 2
#define waves_SponsorFeeTransactionData_min_fee_tag 1
#define waves_MassTransferTransactionData_asset_id_tag 1
#define waves_MassTransferTransactionData_transfers_tag 2
#define waves_MassTransferTransactionData_attachment_tag 3
#define waves_TransferTransactionData_recipient_tag 1
#define waves_TransferTransactionData_amount_tag 2
#define waves_TransferTransactionData_attachment_tag 3
#define waves_Transaction_genesis_tag            101
#define waves_Transaction_payment_tag            102
#define waves_Transaction_issue_tag              103
#define waves_Transaction_transfer_tag           104
#define waves_Transaction_reissue_tag            105
#define waves_Transaction_burn_tag               106
#define waves_Transaction_exchange_tag           107
#define waves_Transaction_lease_tag              108
#define waves_Transaction_lease_cancel_tag       109
#define waves_Transaction_create_alias_tag       110
#define waves_Transaction_mass_transfer_tag      111
#define waves_Transaction_data_transaction_tag   112
#define waves_Transaction_set_script_tag         113
#define waves_Transaction_sponsor_fee_tag        114
#define waves_Transaction_set_asset_script_tag   115
#define waves_Transaction_invoke_script_tag      116
#define waves_Transaction_update_asset_info_tag  117
#define waves_Transaction_chain_id_tag           1
#define waves_Transaction_sender_public_key_tag  2
#define waves_Transaction_fee_tag                3
#define waves_Transaction_timestamp_tag          4
#define waves_Transaction_version_tag            5
#define waves_SignedTransaction_transaction_tag  1
#define waves_SignedTransaction_proofs_tag       2

/* Struct field encoding specification for nanopb */
extern const pb_field_t waves_SignedTransaction_fields[3];
extern const pb_field_t waves_Transaction_fields[23];
extern const pb_field_t waves_GenesisTransactionData_fields[3];
extern const pb_field_t waves_PaymentTransactionData_fields[3];
extern const pb_field_t waves_Attachment_fields[5];
extern const pb_field_t waves_TransferTransactionData_fields[4];
extern const pb_field_t waves_CreateAliasTransactionData_fields[2];
extern const pb_field_t waves_DataTransactionData_fields[2];
extern const pb_field_t waves_DataTransactionData_DataEntry_fields[6];
extern const pb_field_t waves_MassTransferTransactionData_fields[4];
extern const pb_field_t waves_MassTransferTransactionData_Transfer_fields[3];
extern const pb_field_t waves_LeaseTransactionData_fields[3];
extern const pb_field_t waves_LeaseCancelTransactionData_fields[2];
extern const pb_field_t waves_BurnTransactionData_fields[2];
extern const pb_field_t waves_IssueTransactionData_fields[7];
extern const pb_field_t waves_ReissueTransactionData_fields[3];
extern const pb_field_t waves_SetAssetScriptTransactionData_fields[3];
extern const pb_field_t waves_SetScriptTransactionData_fields[2];
extern const pb_field_t waves_ExchangeTransactionData_fields[6];
extern const pb_field_t waves_SponsorFeeTransactionData_fields[2];
extern const pb_field_t waves_InvokeScriptTransactionData_fields[4];
extern const pb_field_t waves_UpdateAssetInfoTransactionData_fields[4];

/* Maximum encoded size of messages (where known) */
/* waves_SignedTransaction_size depends on runtime parameters */
/* waves_Transaction_size depends on runtime parameters */
/* waves_GenesisTransactionData_size depends on runtime parameters */
/* waves_PaymentTransactionData_size depends on runtime parameters */
#define waves_Attachment_size                    143
#define waves_TransferTransactionData_size       (190 + waves_Amount_size)
/* waves_CreateAliasTransactionData_size depends on runtime parameters */
/* waves_DataTransactionData_size depends on runtime parameters */
/* waves_DataTransactionData_DataEntry_size depends on runtime parameters */
/* waves_MassTransferTransactionData_size depends on runtime parameters */
#define waves_MassTransferTransactionData_Transfer_size 49
#define waves_LeaseTransactionData_size          49
/* waves_LeaseCancelTransactionData_size depends on runtime parameters */
#define waves_BurnTransactionData_size           (6 + waves_Amount_size)
/* waves_IssueTransactionData_size depends on runtime parameters */
#define waves_ReissueTransactionData_size        (8 + waves_Amount_size)
/* waves_SetAssetScriptTransactionData_size depends on runtime parameters */
/* waves_SetScriptTransactionData_size depends on runtime parameters */
/* waves_ExchangeTransactionData_size depends on runtime parameters */
#define waves_SponsorFeeTransactionData_size     (6 + waves_Amount_size)
/* waves_InvokeScriptTransactionData_size depends on runtime parameters */
/* waves_UpdateAssetInfoTransactionData_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define TRANSACTION_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
